FROM node:22-alpine AS build
WORKDIR /app
COPY . .
ENV REACT_APP_API_URL=https://i11e102.p.ssafy.io
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/conf.d /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
