name: boss-dev

services:

  frontend:
    build: ./client
    container_name: boss-dev-frontend
    ports:
      - "80:80"

  backend:
    build: ./server/BOSS
    container_name: boss-dev-backend
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: mysql
    container_name: boss-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - TZ=Asia/Seoul
    volumes:
      - ~/mysql_data_dev:/var/lib/mysql:rw
