name: boss-dev

services:
  db:
    image: mysql
    networks:
      - wire

  backend:
    image: boss-backend:latest
    container_name: boss-dev-backend
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - wire


networks:
  wire:
    driver: bridge