name: boss-dev

services:

  frontend:
    build: ./client
    container_name: boss-dev-frontend
    environment:
      - TZ=Asia/Seoul

  backend:
    build: ./server/BOSS
    container_name: boss-dev-backend
    depends_on:
      - db
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: mysql
    container_name: boss-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - TZ=Asia/Seoul
    volumes:
      - ~/mysql_data_dev:/var/lib/mysql:rw
  
  server:
    build: ./nginx
    container_name: boss-dev-nginx
    depends_on:
      - frontend
      - backend
    ports:
      8888:80
    environment:
      - TZ=Asia/Seoul