version: '3.8'

services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: jenkins.dockerfile
    ports:
      - "22222:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket mount