FROM gradle:jdk17-alpine AS build
WORKDIR /builder/
COPY build.gradle /builder/
COPY src /builder/src/
RUN gradle clean build

FROM openjdk:17-jdk-slim
COPY --from=build /builder/build/libs/*.jar /app.jar
ENTRYPOINT [ "java", "-jar", "/app.jar" ]